basePath: 这里写base path
info:
  contact:
    email: support@swagger.io
    name: 这里写联系人信息
    url: http://www.swagger.io/support
  description: douyin
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: api
  version: "1.0"
paths:
  /api/v1/sayHello/{name}:
    get:
      consumes:
      - application/json
      description: sayHello
      parameters:
      - description: name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: name,helloWorld
          schema:
            type: string
swagger: "2.0"
